"""
Generate PDF reports from chatbot results using reportlab.
"""

import io
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_pdf_report(
    name: str,
    score: float,
    readiness_level: str,
    summary: str,
    recommendations: str,
) -> io.BytesIO:
    """Generate a PDF report for a beneficiary's entrepreneurship assessment."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=HexColor("#1a1a1a"),
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=HexColor("#2563eb"),
        spaceBefore=16,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        spaceAfter=8,
    )
    score_style = ParagraphStyle(
        "ScoreStyle",
        parent=styles["Normal"],
        fontSize=28,
        textColor=HexColor("#2563eb"),
        alignment=1,  # center
        spaceAfter=4,
    )

    elements = []

    # Title
    elements.append(Paragraph("Rwanda Youth Entrepreneurship", title_style))
    elements.append(Paragraph("Assessment Report", title_style))
    elements.append(Spacer(1, 12))

    # Info table
    info_data = [
        ["Beneficiary:", name],
        ["Date:", datetime.utcnow().strftime("%B %d, %Y")],
        ["Readiness Level:", readiness_level],
    ]
    info_table = Table(info_data, colWidths=[2 * inch, 4 * inch])
    info_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 16))

    # Score
    elements.append(Paragraph("Entrepreneurship Readiness Score", heading_style))
    elements.append(Paragraph(f"{score:.0f} / 100", score_style))
    elements.append(Paragraph(f"Level: {readiness_level}", ParagraphStyle(
        "LevelCenter", parent=body_style, alignment=1, textColor=HexColor("#6b7280"),
    )))
    elements.append(Spacer(1, 12))

    # Summary
    elements.append(Paragraph("Assessment Summary", heading_style))
    for line in summary.split("\n"):
        line = line.strip()
        if line:
            # Escape XML special characters
            line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            elements.append(Paragraph(line, body_style))

    elements.append(Spacer(1, 8))

    # Recommendations
    elements.append(Paragraph("Recommendations", heading_style))
    for line in recommendations.split("\n"):
        line = line.strip()
        if line:
            line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            elements.append(Paragraph(line, body_style))

    elements.append(Spacer(1, 24))

    # Footer
    footer_style = ParagraphStyle(
        "Footer", parent=body_style, fontSize=9, textColor=HexColor("#9ca3af"), alignment=1,
    )
    elements.append(Paragraph(
        "Generated by Rwanda Youth Training & Employment Platform",
        footer_style,
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer
